### ISSUE TITLE
Icons problem

### ISSUE THREAD

**Issue by akarpych** [artem-sedykh/mini-humidifier#74] opened 2021-11-07 09:58 UTC
![Без имени](https://user-images.githubusercontent.com/73226493/140638650-6ce6a229-203d-442a-9582-f14c25e65c4b.png)
Icons are not displayed after the last HA update.

**Comment by fustom** [comment] 2021-11-07 17:41
I created a pull request to fix this, but it has not been merged yet.
https://github.com/artem-sedykh/mini-humidifier/pull/73

**Comment by alexanderznamensky** [comment] 2021-11-11 09:54
is it possible to add your changes manaully? i can see only /config/www/community/mini-humidifier/mini-humidifier-bundle.js
thanks!

**Comment by strannik-pi** [comment] 2021-11-11 12:56
Icons are not displayed
![Безымянный](https://user-images.githubusercontent.com/60686643/141301724-2a8078ce-6d72-4cb1-8b9f-adaf811b4ef2.jpg)
.

**Comment by fustom** [comment] 2021-11-14 10:36
@alexanderznamensky I was created a release in my fork. You can download the mini-humidifier-bundle.js and replace in your config then refresh your browser. https://github.com/fustom/mini-humidifier/releases/tag/v2.5.5

**Comment by strannik-pi** [comment] 2021-11-15 08:26
It don't work((

**Comment by alexanderznamensky** [comment] 2021-11-15 08:29
unfortunately I can confirm - it is not working.

**Comment by fustom** [comment] 2021-11-15 09:03
That's interesting. It works for me. Are you sure that you replaced the mini-humidifier-bundle.js file in your config/www/community/mini-humidifier/ folder? Did you try to restart ha? Maybe the browser cached the file, try ctr+F5.

**Comment by strannik-pi** [comment] 2021-11-15 10:08
I replaced the file, cleaned the cache and history
![Безымянный](https://user-images.githubusercontent.com/60686643/141762883-bcdbe7f6-4eb6-4f1d-a76a-14417145fc2c.jpg)

**Comment by fustom** [comment] 2021-11-15 17:46
Sorry in that case I really don't have any idea. ![Kazam_screenshot_00005](https://user-images.githubusercontent.com/6751243/141829417-e833cf32-fe5b-404b-9c32-184402602fa2.png)

**Comment by fustom** [comment] 2021-11-15 21:09
Ah I forgot, but you should change the hacstag for your resource in the configuration/dashboard/resources. For example add plus one to the number.
![Kazam_screenshot_00006](https://user-images.githubusercontent.com/6751243/141854080-28a78781-b551-480c-ad8b-d398e233738e.png)
.

**Comment by maddron** [comment] 2021-11-15 21:28
New version worked for me to fix icons, but there is still no target and current humidity
![11](https://user-images.githubusercontent.com/71969832/141856234-98dc1766-cea7-4962-b3f8-9e101dff9e9d.png)

**Comment by vsimanin** [comment] 2021-11-19 19:28
@artem-sedykh please. fix it!!!

**Closed** 2021-11-22 16:12 UTC

**Comment by alexanderznamensky** [comment] 2021-12-01 06:28
What is interesting - in Home Assistant Companion (running on Android) there is no icons....

**Comment by vsimanin** [comment] 2021-12-01 06:55
> What is interesting - in Home Assistant Companion (running on Android) there is no icons....

It's cache. 100%
 change tag in resource.

**Comment by alexanderznamensky** [comment] 2021-12-01 06:59
thx!
But I've no tag in resources:
    - url: /hacsfiles/mini-humidifier/mini-humidifier-bundle.js
      type: module
SHould I add something in the end of url?
